# Generated by Django 4.2.7 on 2025-10-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nomor_telepon_customer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nomor_telepon_supplier',
            field=models.CharField(max_length=50),
        ),
    ]
