# Generated by Django 4.2.7 on 2025-10-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_customer_nomor_telepon_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pallet_penuh',
            old_name='tanggal_wrap',
            new_name='tanggal_event',
        ),
        migrations.RemoveField(
            model_name='pallet_penuh',
            name='id_kebutuhan',
        ),
        migrations.AddField(
            model_name='pallet_penuh',
            name='event_type',
            field=models.CharField(choices=[('AUTO', 'Auto Close'), ('MANUAL', 'Manual Close')], default='AUTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='pallet_penuh',
            name='id_detail_produksi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_menutup', to='inventory.detail_produksi'),
        ),
    ]
