# Generated by Django 4.2.7 on 2025-10-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_tanggal_wrap_pallet_penuh_tanggal_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_produksi',
            name='jumlah_fg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail_produksi',
            name='jumlah_reject',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
