# Generated by Django 4.2.7 on 2025-10-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_detail_produksi_jumlah_fg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebutuhan_pallet',
            name='mm_per_roll',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
