# Generated by Django 4.2.7 on 2025-10-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_kebutuhan_pallet_mm_per_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_produksi',
            name='status_qc',
            field=models.CharField(choices=[('belum', 'Belum diperiksa'), ('sedang', 'Sedang diperiksa'), ('sudah', 'Sudah diperiksa')], default='belum', max_length=10),
        ),
    ]
