# Generated by Django 4.2.7 on 2025-11-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_detail_produksi_status_qc'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='safety_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
