# Generated by Django 4.2.7 on 2025-11-02 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_produk_safety_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet_penuh',
            name='id_detail_pemesanan_produk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.detail_pemesanan_produk'),
        ),
    ]
